name: CI
on:
  push:
    branches: 
      main
  schedule:
    - cron: '*/6 * * * *'
jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.16.0
    - name: Installing Node Dependencies
      run: npm install
    - name: Executing "app.js" File
      run: node app.js
    - run: |
        echo ----------------------
        date
        echo ----------------------
        echo "RUN:$GITHUB_RUN_NUMBER JOB:$GITHUB_JOB"
