name: Worker
on:
  push:
    paths:
      - "worker.js"
      - "workers/**.js"
#   schedule:
#     - cron: "* * * * *"
jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: Installing Node Dependencies
        run: npm install
      - name: Executing "worker.js"
        run: |
          node workers.js
          git config user.email ethereal97@gmail.com
          git config user.name  skmetheloper
          git add .
          git commit -m "Updated at $(date)"
          git push origin main
